name: 'hcl-validator'
description: 'Validate HCL file'
inputs:
  HCL_FILE_PATH:
    description: 'File path for hcl which has to be validated.'
    required: true
runs:
  using: 'node12'
  main: 'main.js'
branding:
  icon: 'lock'
  color: 'orange'